local builtin = require('telescope.builtin')

vim.keymap.set('n', '<leader>ff', builtin.find_files, {desc = "find file"})
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {desc = "live grep"})
vim.keymap.set('n', '<leader>fb', builtin.buffers, {desc = "find buffers"})
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {desc = "find help tags"})
vim.keymap.set('n', '<leader>fs', builtin.lsp_references, {desc = "find refs"})
vim.keymap.set('n', '<leader>fd', builtin.lsp_definitions, {desc = "find defs"})
vim.keymap.set('n', '<leader>fD', builtin.lsp_type_definitions, {desc = "find type_defs"})
vim.keymap.set('n', '<leader>fc', builtin.lsp_incoming_calls, {desc = "find incoming calls"})
vim.keymap.set('n', '<leader>fC', builtin.lsp_outgoing_calls, {desc = "find outgoing calls"})
vim.keymap.set('n', '<leader>fi', builtin.lsp_implementations, {desc = "find implementations"})
